### ISSUE TITLE
redrange limits

### ISSUE THREAD

**Issue by MikeeRead** [agabrown/gaiaedr3-flux-excess-correction#1]
I think maybe the condition should be >=4.0 not > 4.0?
redrange = np.logical_not(do_not_correct) & (bp_rp > 4.0)]
unlikely that it'll be exactly 4.0 but ... (the SQL in the paper shows it as >= 4.0)

**Comment by agabrown** [comment]
Indeed. Thanks for noticing!

This is now fixed in the updated code. Apologies for the slow reaction, busy semester...

**Comment by agabrown** [comment]
fixed.
